### ISSUE TITLE
Gettting Stake-Session-Token; Headers missing authentication token.

### ISSUE THREAD

**Issue by beelzmon** [stabacco/stake-python#126]
Hey, I have been trying to get the API to work but in my request headers to the URL

https://global-prd-api.hellostake.com/api/utils/marketStatus

for example, there isnt any session token. They do appear to have some sort cookie which might contain this info.
Is this some sort of change on Stake's end or am i misunderstanding how to get the header.

Regards,

**Comment by stabacco** [comment]
that endpoint is actually public and does not need any token,
You'll find it at any other url such as:
https://global-prd-api.hellostake.com/api/users/accounts/v2/equityPositions , https://global-prd-api.hellostake.com/api/users/accounts/cashAvailableForWithdrawal, https://global-prd-api.hellostake.com/api/user/additional

**Comment by stabacco** [comment]
@beelzmon Can you advise whether this can be closed?
