### ISSUE TITLE
Exception thrown if rating contains a blank 'pt_prior' field

### ISSUE THREAD

**Issue by GrandSlam90** [stabacco/stake-python#129]
When attempting to get the ratings for 'AAPL' today, I came across the above error. Specifically, I get:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Rating
pt_prior
  value is not a valid float (type=type_error.float)
```
Debugging the data, it appears sometimes the JSON returns the key but with an empty value which I think is what is throwing the exception.
Adding the code below seems to fix things:
```
    pt_prior: Optional[float] = None
+    @pydantic.validator('pt_prior', pre=True)
+    def pt_prior_blank_string(value, field):
+        if value == "":
+            return None
+        return value
    url_calendar: Optional[str] = None
```
Hope this helps.

Thanks for all your hard work.

**Comment by stabacco** [comment]
Thanks @GrandSlam90 for reporting and suggesting a fix. It should now be available in the 0.3.2 release.
Closing this.
