### ISSUE TITLE
Unable to handle merger acquisition transaction

### ISSUE THREAD

**Issue by A13x3i** [stabacco/stake-python#131]
I had a merger acquisition in my account and couldn't import this transaction(others worked fine). Possibly its an problem on stake's end as it doesn't show up in my transaction summary report, however this transaction indeed exists. Here is the error I get when I try to retrieve this specific transaction using a date range

> ...
> File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Transaction
> mergerAcquisition
>   value is not a valid float (type=type_error.float)

I've tried to change Transaction.merger_acquisition:  to Optional[str] but no luck.

**stake 0.3.2**

**Comment by stabacco** [comment]
Can you tell what type of value is being passed in? I don't have any merger_acquisition among my transactions.
