### ISSUE TITLE
Watchlist adding/removing

### ISSUE THREAD

**Issue by YMBahr** [stabacco/stake-python#134]
In Watchlist.py:
The field "watching": request.watching is not required and returns a 400 error.
Perhaps this field should be removed from:
AddToWatchlistRequest
RemoveFromWatchlistRequest
WatchlistClient (payload field)

**Comment by stabacco** [comment]
Thanks for reporting this

**Comment by stabacco** [comment]
Fixed in 0.3.4 release.
