### ISSUE TITLE
Documentation for the API, and interest in a C# project

### ISSUE THREAD

**Issue by DanielAus** [stabacco/stake-python#141]
Is there any documentation for the "Stake RPC api"? 
 - If yes, is the documentation available to the public? 
 - If no, then how did you discover the API?

I use C++ and C#, so I would like to convert your python example into a project written in C#. Would you be interested in a C# project?

**Comment by stabacco** [comment]
Hi Daniel, I don't know of any available documentation, I reverse-engineered the api calls from the browser to try have something working. 
Converting to C# sounds like a good idea, I'm not good at that language but i'd be happy to review some code if that helps

**Comment by spaghettiScreen** [comment]
> I reverse-engineered the api calls from the browser to try have something working

Incredible. Thank you very much for the work you have done on this project :)

Really sucks that Stake has the API in place for internal use by their own client app and website, but don't bother to provide documentation for users' personal use.
