### ISSUE TITLE
Support for ASX

### ISSUE THREAD

**Issue by julianprester** [stabacco/stake-python#142]
First of all thank you for this amazing project.

As I understand it, the project currently only supports the US market? The API endpoints don't seem to match the ASX one's I can see in the Developer Console. Are there any plans for implementing the ASX endpoints?

**Comment by stabacco** [comment]
I should have some free time in the next coming weeks, so I am planning to add ASX  support.
Keep an eye on this issue for updates.

**Comment by julianprester** [comment]
Thanks so much for your work. I haven't tested all calls yet, but it looks very good.
