### ISSUE TITLE
Funding.cash_available values returning None

### ISSUE THREAD

**Issue by jakethesquid** [stabacco/stake-python#150]
Hi, 

Big fan of this package and very appreciative of the work you've done here.

In using the latest version (0.6.0) the fundings.cash_available() class seems to return None for all fields, except for cash_available_for_withdrawal which appears to be working.

I changed the contents of the CashAvailable class back to the previous version I had (contents below) and the problem went away.

class CashAvailable(BaseModel):
    cash_available_for_withdrawal: float
    cash_available_for_trade: float
    cash_balance: float
    reserved_cash: float
    dw_cash_available_for_withdrawal: float
    pending_orders_amount: float
    pending_withdrawals: float
    card_hold_amount: float
    pending_poli_amount: float
    cash_settlement: List[Optional[CashSettlement]]

    class Config:
        alias_generator = camelcase

Any thoughts on why this would be happening?

Cheers,
Jake

**Comment by stabacco** [comment]
I shall take a look,
Can you paste the exact snippet you are using so that I can add a test for
it?
Cheers,

**Comment by stabacco** [comment]
Nevermind, appears like i copied the schema from the asx module by mistake, I'll provide a fix soon

**Comment by jakethesquid** [comment]
Thanks mate!
