### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by zacharydsb** [stabacco/stake-python#44]
Issue with logging in despite correct credentials, probably due to a change in the API. 

Screen shot attached.

![Screen Shot 2020-11-10 at 8 33 49 am](https://user-images.githubusercontent.com/27905855/98602112-1145f100-2334-11eb-8ba9-2782b9f850fe.png)

**Comment by stabacco** [comment]
Looks like the reCAPTCHA protection has been enabled on the api, please resort using the session authentication for the time being ( https://github.com/stabacco/stake-python#using-an-existing-session-token ) .

**Comment by illi4** [comment]
Getting the same issue. Any suggestions on how to overcome the reCAPTCHA protection?

**Comment by stabacco** [comment]
I don't think there is an easy way at the moment, sadly.
My suggestion is to manually login into the stake website and get a `Stake-Session-Token` by inspecting one of the requests headers the Developer tools -> Network. 

you can then login with : 
```
from stake import StakeClient, SessionTokenLoginRequest, CredentialsLoginRequest
import asyncio

login_request = SessionTokenLoginRequest(token="yourtoken")
async def print_user():
    async with StakeClient(login_request) as stake_session:
        print(stake_session.user.first_name)
        print(stake_session.headers.stake_session_token)

asyncio.run(print_user())

```

I've been using this authentication method for many months and it's still working. 
Not sure if there is any way to bypass the reCAPTCHA at this stage, but i will investigate.

**Comment by illi4** [comment]
It's a pity they don't have a proper API. I've faced the same issue using Selenium webdriver, and tried various options today mentioned on the internet (e.g. disabling webdriver flag), but nothing helps.

**Comment by stabacco** [comment]
Yeah It's a pity, indeed. 
Most probably the reCAPTCHA will block any selenium call as well.
